from __future__ import annotations

from pathlib import Path
from typing import Any

import pandas as pd

MAX_SHEET_NAME_LEN = 31
DEFAULT_AMOUNT_FORMAT = "#,##0.00"
DEFAULT_DATE_FORMAT = "yyyy-mm-dd"
DEFAULT_MONTH_FORMAT = "yyyy-mm"


def safe_sheet_name(name: str) -> str:
    forbidden = {"[", "]", ":", "*", "?", "/", "\\"}
    cleaned = "".join("_" if ch in forbidden else ch for ch in str(name)).strip()
    if not cleaned:
        cleaned = "Sheet"
    return cleaned[:MAX_SHEET_NAME_LEN]


def autosize_columns(worksheet: Any, frame: pd.DataFrame, *, min_width: int = 10, max_width: int = 50) -> None:
    for idx, col in enumerate(frame.columns):
        header_len = len(str(col))
        value_len = 0
        if not frame.empty:
            value_len = int(frame[col].astype(str).map(len).max())
        width = max(min_width, min(max_width, max(header_len, value_len) + 2))
        worksheet.set_column(idx, idx, width)


def write_metadata_sheet(writer: pd.ExcelWriter, metadata: dict[str, Any]) -> None:
    workbook = writer.book
    sheet_name = safe_sheet_name("Metadata")
    worksheet = workbook.add_worksheet(sheet_name)
    writer.sheets[sheet_name] = worksheet

    title_format = workbook.add_format({"bold": True, "font_size": 12})
    key_format = workbook.add_format({"bold": True, "bg_color": "#F2F2F2", "border": 1})
    value_format = workbook.add_format({"border": 1})

    worksheet.write(0, 0, "Report Metadata", title_format)
    worksheet.write(2, 0, "Field", key_format)
    worksheet.write(2, 1, "Value", key_format)

    for row_idx, (key, value) in enumerate(metadata.items(), start=3):
        worksheet.write(row_idx, 0, str(key), key_format)
        worksheet.write(row_idx, 1, "" if value is None else str(value), value_format)

    worksheet.freeze_panes(3, 0)
    worksheet.autofilter(2, 0, max(2, len(metadata) + 2), 1)
    worksheet.set_column(0, 0, 30)
    worksheet.set_column(1, 1, 60)
    worksheet.set_tab_color("#4F81BD")


def write_dataframe_sheet(writer: pd.ExcelWriter, sheet_name: str, frame: pd.DataFrame) -> None:
    safe_name = safe_sheet_name(sheet_name)
    frame.to_excel(writer, sheet_name=safe_name, index=False)

    workbook = writer.book
    worksheet = writer.sheets[safe_name]

    header_format = workbook.add_format({"bold": True, "bg_color": "#D9E1F2", "border": 1})
    amount_format = workbook.add_format({"num_format": DEFAULT_AMOUNT_FORMAT})
    date_format = workbook.add_format({"num_format": DEFAULT_DATE_FORMAT})
    month_format = workbook.add_format({"num_format": DEFAULT_MONTH_FORMAT})

    for col_idx, col_name in enumerate(frame.columns):
        worksheet.write(0, col_idx, col_name, header_format)
        col_lower = str(col_name).lower()
        series = frame[col_name]

        if pd.api.types.is_numeric_dtype(series):
            worksheet.set_column(col_idx, col_idx, None, amount_format)
        elif pd.api.types.is_datetime64_any_dtype(series):
            worksheet.set_column(col_idx, col_idx, None, date_format)
        elif "month" in col_lower:
            worksheet.set_column(col_idx, col_idx, None, month_format)

    freeze_col = 1 if len(frame.columns) > 0 else 0
    worksheet.freeze_panes(1, freeze_col)
    if len(frame.columns) > 0:
        worksheet.autofilter(0, 0, max(1, len(frame)), len(frame.columns) - 1)
    autosize_columns(worksheet, frame)


def format_workbook(writer: pd.ExcelWriter) -> None:
    writer.book.set_properties({"comments": "Generated by ACPL automation"})


def build_excel_report_pack(
    output_file: str | Path,
    report_dict: dict[str, pd.DataFrame],
    metadata: dict[str, Any] | None = None,
) -> None:
    output_path = Path(output_file)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    with pd.ExcelWriter(output_path, engine="xlsxwriter") as writer:
        format_workbook(writer)

        if metadata:
            write_metadata_sheet(writer, metadata)

        for sheet_name, frame in report_dict.items():
            if not isinstance(frame, pd.DataFrame):
                raise TypeError(f"Report '{sheet_name}' must be a pandas DataFrame")
            write_dataframe_sheet(writer, sheet_name, frame)
